(prn (for [x (range 6) :when (odd? x)] (* x x)))
(prn (for [x [1 2 3] y [:a :b] :let [p [x y]] :when (not= x 2)] p))
(prn (for [x (range 10) :while (< x 3) y [0 1]] (+ x y)))
(prn (for [[k v] {:a 1 :b 2}] (str k v)))
(doseq [x [1 2] y [:p :q]] (print x y ""))
(println)
(doseq [[k v] {:a 1 :b 2} :when (odd? v) :let [s (str k "=" v)]] (println s))
(doseq [x (range 10) :while (< x 3)] (print x))
(println)
(when-let [[a b] [1 2]] (println (+ a b)))
(prn (if-let [{:keys [x]} nil] x :none) (if-let [{:keys [x]} {:x 5}] x :none))
