(require '[clojure.edn :as edn] '[clojure.set :as set])

(println (compare 1 2) (compare "b" "a") (compare :a/b :a/c) (compare [1 2] [1 3]) (compare nil 1))
(prn (sort [3 1 2]) (sort > [3 1 2]) (sort-by :n [{:n 2} {:n 1}]) (sort-by count > ["a" "abc" "ab"]))
(prn (sort ["b" "a" "c"]) (sort [:b :a/z :a]))
(prn (merge {:a 1} nil {:b 2} {:a 3}) (merge-with + {:a 1} {:a 2 :b 1}))
(prn (zipmap [:a :b] [1 2]) (select-keys {:a 1 :b 2} [:a :z]) (disj #{1 2 3} 2))
(prn (namespace :a/b) (namespace :b) (name :a/b) (keyword "x" "y") (symbol "x" "y"))
(prn (assoc-in {} [:a :b] 1) (update-in {:a {:b 1}} [:a :b] + 10) (get-in {:a {:b 1}} [:a :b]))
(prn (peek [1 2 3]) (pop [1 2 3]) (subvec [1 2 3 4] 1 3) (find {:a 1} :a) (keys nil))
(prn (keep #(when (odd? %) (* % 10)) [1 2 3]) (max-key count "ab" "abc" "a") (ffirst [[1 2]]) (butlast [1 2 3]))
(prn (distinct [1 2 1 3 2]) (interleave [1 2] [:a :b]) (flatten [1 [2 [3]] 4]) (not-empty []) (empty {:a 1}))
(prn (set/union #{1} #{2}) (set/intersection #{1 2} #{2 3}) (set/difference #{1 2} #{2}) (set/subset? #{1} #{1 2}))
(prn (reduce-kv (fn [acc k v] (+ acc v)) 0 {:a 1 :b 2}) ((complement even?) 3) ((fnil inc 0) nil))
(prn (read-string "[1 :a \"s\" {:k #{2}}]"))
(prn (edn/read-string {:readers {'db/id (fn [v] [:tempid v])}} "#db/id [:db.part/user -1]"))
(prn (edn/read-string {:default (fn [t v] [t v])} "#foo/bar 7"))
(def t (edn/read-string "#inst \"2020-01-02T03:04:05.678-00:00\""))
(prn t (inst-ms t) (inst? t) (= t (java.util.Date. (inst-ms t))))
(prn (edn/read-string "#inst \"1970-01-01\"") (edn/read-string "#inst \"2020-01-01T00:00:00+01:00\""))
(println (str (java.util.Date. 0)))
(def u (parse-uuid "550e8400-e29b-41d4-a716-446655440000"))
(prn u (uuid? u) (= u (edn/read-string "#uuid \"550E8400-E29B-41D4-A716-446655440000\"")) (str u))
(prn (compare (java.util.Date. 1) (java.util.Date. 2)) (uuid? (random-uuid)))
(try (throw (ex-info "boom" {:code 7}))
  (catch Exception e (prn (ex-message e) (ex-data e))))
