(def n 20000)
(let [t0 (now-ms)
      v  (reduce conj [] (range n))
      t1 (now-ms)
      m  (reduce (fn [acc i] (assoc acc i i)) {} (range n))
      t2 (now-ms)
      s  (reduce conj #{} (range n))
      t3 (now-ms)
      g  (reduce (fn [acc i] (+ acc (get m i))) 0 (range n))
      t4 (now-ms)]
  (println "vector conj x" n ":" (- t1 t0) "ms")
  (println "map assoc  x" n ":" (- t2 t1) "ms")
  (println "set conj   x" n ":" (- t3 t2) "ms")
  (println "map get    x" n ":" (- t4 t3) "ms  sum" g)
  (println "counts" (count v) (count m) (count s)))
